services:
  - name: fastapi-app
    type: web
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port 10000
